// ═══════════════════════════════════════════
// DATA CONSTANTS
// ═══════════════════════════════════════════

const TEAMS = [
  { id: 'senga',   name: 'Busch Latte',                 pick: 1, manager: '' },
  { id: 'skenes',  name: "Skenes'n on deez Hoerners",  pick: 2, manager: '' },
  { id: 'glas',    name: 'The Ragans Administration',   pick: 3, manager: 'TylerV' },        // fka 877-Glas-Now
  { id: 'lets',    name: 'Ete Crow',                     pick: 4, manager: 'Jace Allison' }, // fka LetsPlayMajorLeagueBaseball
  { id: 'keanu',   name: 'Keanu Reeves',                pick: 5, manager: '' },
  { id: 'vibes',   name: 'Good Vibes Only',             pick: 6, manager: '' },
  { id: 'rain',    name: 'Rain City Bombers',           pick: 7, manager: '' },
  { id: 'buckner', name: 'The Buckner Boots',           pick: 8, manager: 'Michael' },
  { id: 'decoy',   name: 'Ray Donovan',                       pick: 9, manager: '' },
  { id: 'oneball', name: 'One Ball Two Strikes',        pick: 10, manager: '' },
];

const STANDINGS_2025 = [
  { teamId: 'lets',    rank: 1, record: '123-71-16', pct: '.624', moves: 81 },
  { teamId: 'oneball', rank: 2, record: '117-76-17', pct: '.598', moves: 63 },
  { teamId: 'glas',    rank: 3, record: '105-92-13', pct: '.531', moves: 94 },
  { teamId: 'vibes',   rank: 4, record: '99-98-13',  pct: '.502', moves: 101 },
  { teamId: 'decoy',   rank: 5, record: '107-89-14', pct: '.543', moves: 92 },
  { teamId: 'keanu',   rank: 6, record: '109-92-9',  pct: '.540', moves: 36 },
  { teamId: 'senga',   rank: 7, record: '85-115-10', pct: '.429', moves: 60 }, // fka Senga man watchu smokin?
  { teamId: 'buckner', rank: 8, record: '70-119-21', pct: '.383', moves: 50 },
  { teamId: 'rain',    rank: 9, record: '80-118-12', pct: '.410', moves: 17 },
  { teamId: 'skenes',  rank: 10, record: '87-112-11', pct: '.440', moves: 82 },
];

const REPEAT_PICKS = [
  { player: 'Adley Rutschman',    teamId: 'buckner', r25: 7,  r26: 12, diff: 5 },
  { player: 'Cristopher Sánchez', teamId: 'keanu',   r25: 14, r26: 3,  diff: -11 },
  { player: 'Jesús Luzardo',      teamId: 'lets',    r25: 19, r26: 7,  diff: -12 },
  { player: 'Joe Ryan',           teamId: 'lets',    r25: 8,  r26: 6,  diff: -2 },
  { player: 'Ozzie Albies',       teamId: 'lets',    r25: 5,  r26: 12, diff: 7 },
  { player: 'Brent Rooker',       teamId: 'vibes',   r25: 7,  r26: 4,  diff: -3 },
  { player: 'Eugenio Suárez',     teamId: 'vibes',   r25: 16, r26: 11, diff: -5 },
  { player: 'Corbin Burnes',      teamId: 'vibes',   r25: 4,  r26: 23, diff: 19 },
  { player: 'Michael King',       teamId: 'glas',    r25: 6,  r26: 15, diff: 9 },
  { player: 'Robert Suarez',      teamId: 'glas',    r25: 15, r26: 18, diff: 3 },
  { player: 'Carlos Rodón',       teamId: 'oneball', r25: 14, r26: 19, diff: 5 },
  { player: 'Will Smith',         teamId: 'rain',    r25: 13, r26: 13, diff: 0 },
  { player: 'Roki Sasaki',        teamId: 'rain',    r25: 10, r26: 22, diff: 12 },
  { player: 'Kyle Manzardo',      teamId: 'senga',   r25: 21, r26: 22, diff: 1 },
  { player: 'Zach Eflin',         teamId: 'decoy',   r25: 15, r26: 20, diff: 5 },
];

const BUCKNER_2026 = [
  { round: 1, pick: 8, player: 'Kyle Tucker', pos: 'OF', note: '' },
  { round: 2, pick: 13, player: 'Gunnar Henderson', pos: 'SS', note: '' },
  { round: 3, pick: 28, player: 'Ketel Marte', pos: '2B', note: '' },
  { round: 4, pick: 33, player: 'Logan Webb', pos: 'SP', note: '' },
  { round: 5, pick: 48, player: 'Framber Valdez', pos: 'SP', note: 'QS machine' },
  { round: 6, pick: 53, player: 'Chris Sale', pos: 'SP', note: 'K upside' },
  { round: 7, pick: 68, player: 'CJ Abrams', pos: 'SS', note: '' },
  { round: 8, pick: 73, player: 'Corey Seager', pos: 'SS', note: 'Steal of draft' },
  { round: 9, pick: 88, player: 'Devin Williams', pos: 'RP', note: 'Closer 1' },
  { round: 10, pick: 93, player: 'Alex Bregman', pos: '3B', note: 'OBP anchor' },
  { round: 11, pick: 108, player: 'Steven Kwan', pos: 'OF', note: 'OBP/SB' },
  { round: 12, pick: 113, player: 'Adley Rutschman', pos: 'C', note: '2025 keeper' },
  { round: 13, pick: 128, player: 'Daniel Palencia', pos: 'RP', note: 'Closer 2' },
  { round: 14, pick: 133, player: 'Yandy Díaz', pos: '1B', note: 'OBP elite' },
  { round: 15, pick: 148, player: 'Trevor Rogers', pos: 'SP', note: '' },
  { round: 16, pick: 153, player: 'Brandon Nimmo', pos: 'OF', note: 'OBP depth' },
  { round: 17, pick: 168, player: 'Cade Horton', pos: 'SP', note: '' },
  { round: 18, pick: 173, player: 'Munetaka Murakami', pos: '1B', elig: ['1B','3B'], note: 'Power upside' },
  { round: 19, pick: 188, player: 'Colton Cowser', pos: 'OF', note: '' },
  { round: 20, pick: 193, player: 'Robby Snelling', pos: 'SP', note: '' },
  { round: 21, pick: 208, player: 'Joey Cantillo', pos: 'SP', elig: ['SP','RP'], note: '' },
  { round: 22, pick: 213, player: 'Parker Messick', pos: 'SP', note: 'Opening Day rotation' },
  { round: 23, pick: 228, player: 'Jack Leiter', pos: 'SP', note: '' },
];

const TEAM_GRADES = [
  { teamId: 'oneball', grade: 'A',
    analysis: '<strong>Best all-around draft.</strong> Skubal + Yamamoto elite SP duo. Ramírez anchors everywhere including SB/OBP. Olson/Duran/Greene power depth. Bednar + Jansen lock down SV. Late adds (Burns, Eovaldi) fill rotation with high-floor arms.',
    strengths: ['HR','RBI','K','QS','SV','OBP'], weaknesses: ['C depth'] },
  { teamId: 'vibes', grade: 'A-',
    analysis: '<strong>OBP monster with elite SP depth.</strong> Harper/Betts/Altuve best OBP trio in the league. Crochet anchors 10+ deep SP corps (Bradish, Cease, Gore, Pepiot, Bieber, Schwellenbach, Burnes). Drafted Corbin Burnes again in R23 — 19 rounds later than 2025\'s R4 pick.',
    strengths: ['OBP','ERA','WHIP','QS','K','SP depth'], weaknesses: ['SB','OF depth'] },
  { teamId: 'buckner', grade: 'A-',
    analysis: '<strong>Best OBP-format exploitation.</strong> Tucker/Henderson 1-2 punch is elite. Marte/Bregman/Kwan/Rutschman/Nimmo/Cowser project for league\'s highest OBP. Webb + Valdez + Sale = QS factory. Williams + Palencia lock SV. 6 late SP lottery tickets for upside. Only Rutschman returns from 2025.',
    strengths: ['OBP','QS','SV','R','depth'], weaknesses: ['1B power','SB depth'] },
  { teamId: 'decoy', grade: 'B+',
    analysis: '<strong>Mason Miller is the league\'s best closer.</strong> Acuña bounce-back potential makes this boom-or-bust. Cole/Glasnow/Snell elite SP trio when healthy. Risk is health — Acuña, Glasnow, Cole all fragile. If healthy, this is an A team.',
    strengths: ['SV','K','SP upside','HR'], weaknesses: ['health risk','OBP','C'] },
  { teamId: 'glas', grade: 'B+',
    analysis: '<strong>Judge + Ohtani (Pitcher) most unique two-way stack.</strong> Ragans/Castillo/Ohtani(P) elite K upside. SP depth runs through Woodruff, McClanahan, Sheehan, King, Gallen, Keller. Re-drafted Michael King (R6→R15) and Robert Suarez (R15→R18). Pitching volume is absurd.',
    strengths: ['K','QS','ERA','WHIP','HR'], weaknesses: ['SB','MI health','OF depth'] },
  { teamId: 'lets', grade: 'B',
    analysis: '<strong>The defending champs ran it back.</strong> Drafted Elly again (now R1 vs R7 in 2025). Kept Joe Ryan (R8→R6), Luzardo (R19→R7), and Albies (R5→R12). 3 closers (Iglesias, Estévez, Hader) lock SV. SP depth is the worry — no true ace after Ryan/Luzardo.',
    strengths: ['SB','SV','HR','RBI'], weaknesses: ['K','QS','SP depth','ERA risk'] },
  { teamId: 'keanu', grade: 'B',
    analysis: '<strong>Soto + Schwarber best OBP duo outside Buckner.</strong> Promoted Cristopher Sánchez 11 rounds (R14→R3) — biggest single-player bet in the draft. Fried/Peralta give K upside. Chapman + Fairbanks provide saves. Middle is volatile (Buxton, Luis Robert, Merrill).',
    strengths: ['OBP','HR','SV','QS'], weaknesses: ['consistency','SB','C'] },
  { teamId: 'skenes', grade: 'B',
    analysis: '<strong>Witt/Yordan/Devers/Freeman most loaded power core.</strong> Complete roster overhaul — zero repeat picks from 2025 (only team to do this). Muñoz saves, Gilbert/Gausman/Pivetta/Bibee SP depth. Back half is dart throws (Edwards, Rafaela, Barger, García).',
    strengths: ['HR','R','RBI','SV'], weaknesses: ['C depth','SP ace','ERA risk','OBP'] },
  { teamId: 'rain', grade: 'B-',
    analysis: '<strong>Skenes elite SP1 but health risk everywhere.</strong> deGrom/Wheeler/Imanaga good but injury-prone. Tatis/Lindor star power in lineup but Machado/Yelich declining. Only 17 waiver moves in 2025 — fewest in the league. Kept Will Smith in the exact same round (R13→R13) and Sasaki (R10→R22).',
    strengths: ['K','QS','HR','R'], weaknesses: ['SV','health risk','waiver activity'] },
  { teamId: 'senga', grade: 'C+',
    analysis: '<strong>Ohtani (Batter) carries everything.</strong> Rebranded from "Senga man watchu smokin?" to Busch Latte. Carroll/Chisholm/Springer give speed, Díaz locks saves. But SP depth is genuinely concerning — Hunter Brown and Kirby are fine, after that it\'s Strider (health), Imai, Bryce Miller, Bubic, Bello.',
    strengths: ['SB','SV','OBP'], weaknesses: ['SP depth','K','QS','2nd star'] },
];

// PROJECTED STANDINGS DATA (500 sim avg, v3 — 8 pitching slots, full position eligibility)
const PROJECTED = [
  { teamId: 'oneball', w: 134, l: 80, t: 6, pct: '.622', playoff: '100%', champ: '43.4%' },
  { teamId: 'vibes',   w: 126, l: 88, t: 6, pct: '.586', playoff: '100%', champ: '23.8%' },
  { teamId: 'glas',    w: 120, l: 94, t: 6, pct: '.559', playoff: '100%', champ: '15.4%' },
  { teamId: 'buckner', w: 118, l: 97, t: 6, pct: '.547', playoff: '98%',  champ: '12.6%' },
  { teamId: 'decoy',   w: 107, l: 107, t: 6, pct: '.500', playoff: '79%', champ: '2.8%' },
  { teamId: 'keanu',   w: 101, l: 113, t: 6, pct: '.472', playoff: '45%', champ: '1.4%' },
  { teamId: 'lets',    w: 100, l: 115, t: 6, pct: '.466', playoff: '33%', champ: '0.0%' },
  { teamId: 'skenes',  w: 99,  l: 115, t: 6, pct: '.463', playoff: '33%', champ: '0.6%' },
  { teamId: 'rain',    w: 94,  l: 120, t: 6, pct: '.440', playoff: '11%', champ: '0.0%' },
  { teamId: 'senga',   w: 73,  l: 142, t: 5, pct: '.343', playoff: '0%',  champ: '0.0%' },
];

const BUCKNER_SCHEDULE = [
  { week: 1, opp: 'oneball', diff: 'tough' },
  { week: 2, opp: 'lets', diff: 'even' },
  { week: 3, opp: 'senga', diff: 'easy' },
  { week: 4, opp: 'skenes', diff: 'easy' },
  { week: 5, opp: 'vibes', diff: 'tough' },
  { week: 6, opp: 'decoy', diff: 'even' },
  { week: 7, opp: 'keanu', diff: 'even' },
  { week: 8, opp: 'glas', diff: 'even' },
  { week: 9, opp: 'rain', diff: 'easy' },
  { week: 10, opp: 'oneball', diff: 'tough' },
  { week: 11, opp: 'lets', diff: 'even' },
  { week: 12, opp: 'senga', diff: 'easy' },
  { week: 13, opp: 'skenes', diff: 'easy' },
  { week: 14, opp: 'vibes', diff: 'tough' },
  { week: 15, opp: 'decoy', diff: 'even' },
  { week: 16, opp: 'keanu', diff: 'even' },
  { week: 17, opp: 'glas', diff: 'even' },
  { week: 18, opp: 'rain', diff: 'easy' },
  { week: 19, opp: 'oneball', diff: 'tough' },
  { week: 20, opp: 'lets', diff: 'even' },
  { week: 21, opp: 'senga', diff: 'easy' },
  { week: 22, opp: 'skenes', diff: 'easy' },
];
const DRAFT_PICKS = [
  { overall: 1, round: 1, pickInRound: 1, teamId: 'senga', player: 'Shohei Ohtani (Batter)', pos: 'OF', elig: ['Util'], cats: 'HR/R/RBI/SB/OBP' },
  { overall: 2, round: 1, pickInRound: 2, teamId: 'skenes', player: 'Bobby Witt Jr.', pos: 'SS', cats: 'HR/R/RBI/SB' },
  { overall: 3, round: 1, pickInRound: 3, teamId: 'glas', player: 'Aaron Judge', pos: 'OF', cats: 'HR/R/RBI/OBP' },
  { overall: 4, round: 1, pickInRound: 4, teamId: 'lets', player: 'Elly De La Cruz', pos: 'SS', cats: 'HR/R/RBI/SB' },
  { overall: 5, round: 1, pickInRound: 5, teamId: 'keanu', player: 'Juan Soto', pos: 'OF', cats: 'HR/R/RBI/OBP' },
  { overall: 6, round: 1, pickInRound: 6, teamId: 'vibes', player: 'Julio Rodríguez', pos: 'OF', cats: 'HR/R/RBI/SB' },
  { overall: 7, round: 1, pickInRound: 7, teamId: 'rain', player: 'Paul Skenes', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 8, round: 1, pickInRound: 8, teamId: 'buckner', player: 'Kyle Tucker', pos: 'OF', cats: 'HR/R/RBI/SB' },
  { overall: 9, round: 1, pickInRound: 9, teamId: 'decoy', player: 'Ronald Acuña Jr.', pos: 'OF', cats: 'HR/R/RBI/SB' },
  { overall: 10, round: 1, pickInRound: 10, teamId: 'oneball', player: 'Tarik Skubal', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 11, round: 2, pickInRound: 1, teamId: 'oneball', player: 'José Ramírez', pos: '3B', cats: 'HR/R/RBI/SB/OBP' },
  { overall: 12, round: 2, pickInRound: 2, teamId: 'decoy', player: 'Junior Caminero', pos: '3B', cats: 'HR/R/RBI' },
  { overall: 13, round: 2, pickInRound: 3, teamId: 'buckner', player: 'Gunnar Henderson', pos: 'SS', cats: 'HR/R/RBI/SB' },
  { overall: 14, round: 2, pickInRound: 4, teamId: 'rain', player: 'Fernando Tatis Jr.', pos: 'OF', cats: 'HR/R/RBI/SB' },
  { overall: 15, round: 2, pickInRound: 5, teamId: 'vibes', player: 'Garrett Crochet', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 16, round: 2, pickInRound: 6, teamId: 'keanu', player: 'Kyle Schwarber', pos: 'OF', cats: 'HR/R/RBI/OBP' },
  { overall: 17, round: 2, pickInRound: 7, teamId: 'lets', player: 'Vladimir Guerrero Jr.', pos: '1B', cats: 'HR/R/RBI' },
  { overall: 18, round: 2, pickInRound: 8, teamId: 'glas', player: 'Cal Raleigh', pos: 'C', cats: 'HR/R/RBI' },
  { overall: 19, round: 2, pickInRound: 9, teamId: 'skenes', player: 'Yordan Alvarez', pos: 'OF', cats: 'HR/R/RBI/OBP' },
  { overall: 20, round: 2, pickInRound: 10, teamId: 'senga', player: 'Corbin Carroll', pos: 'OF', cats: 'R/SB/OBP' },
  { overall: 21, round: 3, pickInRound: 1, teamId: 'senga', player: 'Jazz Chisholm Jr.', pos: '2B', elig: ['2B','3B'], elig: ['2B','3B'], cats: 'HR/R/RBI/SB' },
  { overall: 22, round: 3, pickInRound: 2, teamId: 'skenes', player: 'Logan Gilbert', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 23, round: 3, pickInRound: 3, teamId: 'glas', player: 'Nick Kurtz', pos: '1B', cats: 'HR/R/RBI' },
  { overall: 24, round: 3, pickInRound: 4, teamId: 'lets', player: 'Jackson Chourio', pos: 'OF', cats: 'HR/R/RBI/SB' },
  { overall: 25, round: 3, pickInRound: 5, teamId: 'keanu', player: 'Cristopher Sánchez', pos: 'SP', cats: 'ERA/WHIP/QS' },
  { overall: 26, round: 3, pickInRound: 6, teamId: 'vibes', player: 'Pete Alonso', pos: '1B', cats: 'HR/R/RBI' },
  { overall: 27, round: 3, pickInRound: 7, teamId: 'rain', player: 'Francisco Lindor', pos: 'SS', cats: 'HR/R/RBI/SB' },
  { overall: 28, round: 3, pickInRound: 8, teamId: 'buckner', player: 'Ketel Marte', pos: '2B', cats: 'HR/R/RBI/OBP' },
  { overall: 29, round: 3, pickInRound: 9, teamId: 'decoy', player: 'Bryan Woo', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 30, round: 3, pickInRound: 10, teamId: 'oneball', player: 'Yoshinobu Yamamoto', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 31, round: 4, pickInRound: 1, teamId: 'oneball', player: 'Matt Olson', pos: '1B', cats: 'HR/R/RBI' },
  { overall: 32, round: 4, pickInRound: 2, teamId: 'decoy', player: 'James Wood', pos: 'OF', cats: 'HR/R/RBI/OBP' },
  { overall: 33, round: 4, pickInRound: 3, teamId: 'buckner', player: 'Logan Webb', pos: 'SP', cats: 'ERA/WHIP/QS' },
  { overall: 34, round: 4, pickInRound: 4, teamId: 'rain', player: 'Manny Machado', pos: '3B', cats: 'HR/R/RBI' },
  { overall: 35, round: 4, pickInRound: 5, teamId: 'vibes', player: 'Brent Rooker', pos: 'OF', cats: 'HR/R/RBI' },
  { overall: 36, round: 4, pickInRound: 6, teamId: 'keanu', player: 'Zach Neto', pos: 'SS', cats: 'HR/R/RBI/SB' },
  { overall: 37, round: 4, pickInRound: 7, teamId: 'lets', player: 'Pete Crow-Armstrong', pos: 'OF', cats: 'HR/R/SB' },
  { overall: 38, round: 4, pickInRound: 8, teamId: 'glas', player: 'Trea Turner', pos: 'SS', cats: 'HR/R/RBI/SB' },
  { overall: 39, round: 4, pickInRound: 9, teamId: 'skenes', player: 'Freddie Freeman', pos: '1B', cats: 'HR/R/RBI/OBP' },
  { overall: 40, round: 4, pickInRound: 10, teamId: 'senga', player: 'Hunter Brown', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 41, round: 5, pickInRound: 1, teamId: 'senga', player: 'George Kirby', pos: 'SP', cats: 'ERA/WHIP/QS' },
  { overall: 42, round: 5, pickInRound: 2, teamId: 'skenes', player: 'Rafael Devers', pos: '1B', cats: 'HR/R/RBI' },
  { overall: 43, round: 5, pickInRound: 3, teamId: 'glas', player: 'Cole Ragans', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 44, round: 5, pickInRound: 4, teamId: 'lets', player: 'Cody Bellinger', pos: 'OF', cats: 'HR/R/RBI/SB' },
  { overall: 45, round: 5, pickInRound: 5, teamId: 'keanu', player: 'Max Fried', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 46, round: 5, pickInRound: 6, teamId: 'vibes', player: 'Bryce Harper', pos: '1B', cats: 'HR/R/RBI/OBP' },
  { overall: 47, round: 5, pickInRound: 7, teamId: 'rain', player: 'Roman Anthony', pos: 'OF', cats: 'HR/R/OBP' },
  { overall: 48, round: 5, pickInRound: 8, teamId: 'buckner', player: 'Framber Valdez', pos: 'SP', cats: 'ERA/WHIP/QS' },
  { overall: 49, round: 5, pickInRound: 9, teamId: 'decoy', player: 'Brice Turang', pos: '2B', cats: 'R/SB' },
  { overall: 50, round: 5, pickInRound: 10, teamId: 'oneball', player: 'Jarren Duran', pos: 'OF', cats: 'HR/R/RBI/SB' },
  { overall: 51, round: 6, pickInRound: 1, teamId: 'oneball', player: 'Riley Greene', pos: 'OF', cats: 'HR/R/RBI/SB' },
  { overall: 52, round: 6, pickInRound: 2, teamId: 'decoy', player: 'Mason Miller', pos: 'RP', cats: 'SV/K/ERA/WHIP' },
  { overall: 53, round: 6, pickInRound: 3, teamId: 'buckner', player: 'Chris Sale', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 54, round: 6, pickInRound: 4, teamId: 'rain', player: 'Jacob deGrom', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 55, round: 6, pickInRound: 5, teamId: 'vibes', player: 'Mookie Betts', pos: 'SS', cats: 'HR/R/RBI/SB/OBP' },
  { overall: 56, round: 6, pickInRound: 6, teamId: 'keanu', player: 'Josh Naylor', pos: '1B', cats: 'HR/R/RBI' },
  { overall: 57, round: 6, pickInRound: 7, teamId: 'lets', player: 'Joe Ryan', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 58, round: 6, pickInRound: 8, teamId: 'glas', player: 'Wyatt Langford', pos: 'OF', cats: 'HR/R/RBI/SB' },
  { overall: 59, round: 6, pickInRound: 9, teamId: 'skenes', player: 'Andrés Muñoz', pos: 'RP', cats: 'SV/K/ERA/WHIP' },
  { overall: 60, round: 6, pickInRound: 10, teamId: 'senga', player: 'William Contreras', pos: 'C', cats: 'HR/R/RBI' },
  { overall: 61, round: 7, pickInRound: 1, teamId: 'senga', player: 'Edwin Díaz', pos: 'RP', cats: 'SV/K/ERA/WHIP' },
  { overall: 62, round: 7, pickInRound: 2, teamId: 'skenes', player: 'Oneil Cruz', pos: 'OF', cats: 'HR/R/RBI/SB' },
  { overall: 63, round: 7, pickInRound: 3, teamId: 'glas', player: 'Austin Riley', pos: '3B', cats: 'HR/R/RBI' },
  { overall: 64, round: 7, pickInRound: 4, teamId: 'lets', player: 'Jesús Luzardo', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 65, round: 7, pickInRound: 5, teamId: 'keanu', player: 'Freddy Peralta', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 66, round: 7, pickInRound: 6, teamId: 'vibes', player: 'Kyle Bradish', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 67, round: 7, pickInRound: 7, teamId: 'rain', player: 'Maikel Garcia', pos: '2B', elig: ['2B','3B','SS','OF'], cats: 'R/SB' },
  { overall: 68, round: 7, pickInRound: 8, teamId: 'buckner', player: 'CJ Abrams', pos: 'SS', cats: 'R/SB/OBP' },
  { overall: 69, round: 7, pickInRound: 9, teamId: 'decoy', player: 'Vinnie Pasquantino', pos: '1B', cats: 'HR/R/RBI/OBP' },
  { overall: 70, round: 7, pickInRound: 10, teamId: 'oneball', player: 'Geraldo Perdomo', pos: 'SS', cats: 'R/SB/OBP' },
  { overall: 71, round: 8, pickInRound: 1, teamId: 'oneball', player: 'Shea Langeliers', pos: 'C', cats: 'HR/RBI' },
  { overall: 72, round: 8, pickInRound: 2, teamId: 'decoy', player: 'Hunter Goodman', pos: 'C', cats: 'HR/RBI' },
  { overall: 73, round: 8, pickInRound: 3, teamId: 'buckner', player: 'Corey Seager', pos: 'SS', cats: 'HR/R/RBI/OBP' },
  { overall: 74, round: 8, pickInRound: 4, teamId: 'rain', player: 'Cade Smith', pos: 'RP', cats: 'SV/ERA/WHIP' },
  { overall: 75, round: 8, pickInRound: 5, teamId: 'vibes', player: 'Dylan Cease', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 76, round: 8, pickInRound: 6, teamId: 'keanu', player: 'Jackson Merrill', pos: 'OF', cats: 'HR/R/RBI/SB' },
  { overall: 77, round: 8, pickInRound: 7, teamId: 'lets', player: 'Nolan McLean', pos: 'SP', cats: 'K/ERA/WHIP' },
  { overall: 78, round: 8, pickInRound: 8, teamId: 'glas', player: 'Shohei Ohtani (Pitcher)', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 79, round: 8, pickInRound: 9, teamId: 'skenes', player: 'Nick Pivetta', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 80, round: 8, pickInRound: 10, teamId: 'senga', player: 'Jacob Misiorowski', pos: 'SP', cats: 'K/ERA/WHIP' },
  { overall: 81, round: 9, pickInRound: 1, teamId: 'senga', player: 'Randy Arozarena', pos: 'OF', cats: 'HR/R/RBI/SB' },
  { overall: 82, round: 9, pickInRound: 2, teamId: 'skenes', player: 'Kevin Gausman', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 83, round: 9, pickInRound: 3, teamId: 'glas', player: 'Jhoan Duran', pos: 'RP', cats: 'SV/K/ERA/WHIP' },
  { overall: 84, round: 9, pickInRound: 4, teamId: 'lets', player: 'Sonny Gray', pos: 'SP', cats: 'ERA/WHIP/QS' },
  { overall: 85, round: 9, pickInRound: 5, teamId: 'keanu', player: 'Byron Buxton', pos: 'OF', cats: 'HR/R/RBI/SB' },
  { overall: 86, round: 9, pickInRound: 6, teamId: 'vibes', player: 'Ben Rice', pos: '1B', elig: ['C','1B'], cats: 'HR/R/RBI/OBP' },
  { overall: 87, round: 9, pickInRound: 7, teamId: 'rain', player: 'Tyler Soderstrom', pos: 'OF', elig: ['1B','OF'], cats: 'HR/R/RBI' },
  { overall: 88, round: 9, pickInRound: 8, teamId: 'buckner', player: 'Devin Williams', pos: 'RP', cats: 'SV/K/ERA/WHIP' },
  { overall: 89, round: 9, pickInRound: 9, teamId: 'decoy', player: 'Tyler Glasnow', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 90, round: 9, pickInRound: 10, teamId: 'oneball', player: 'Bo Bichette', pos: 'SS', cats: 'HR/R/RBI/SB' },
  { overall: 91, round: 10, pickInRound: 1, teamId: 'oneball', player: 'David Bednar', pos: 'RP', cats: 'SV/ERA/WHIP' },
  { overall: 92, round: 10, pickInRound: 2, teamId: 'decoy', player: 'Blake Snell', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 93, round: 10, pickInRound: 3, teamId: 'buckner', player: 'Alex Bregman', pos: '3B', cats: 'HR/R/RBI/OBP' },
  { overall: 94, round: 10, pickInRound: 4, teamId: 'rain', player: 'Christian Yelich', pos: 'OF', cats: 'HR/R/RBI/OBP' },
  { overall: 95, round: 10, pickInRound: 5, teamId: 'vibes', player: 'Jose Altuve', pos: '2B', elig: ['2B','OF'], cats: 'HR/R/RBI/SB/OBP' },
  { overall: 96, round: 10, pickInRound: 6, teamId: 'keanu', player: 'Aroldis Chapman', pos: 'RP', cats: 'SV/K/ERA/WHIP' },
  { overall: 97, round: 10, pickInRound: 7, teamId: 'lets', player: 'Eury Pérez', pos: 'SP', cats: 'K/ERA/WHIP' },
  { overall: 98, round: 10, pickInRound: 8, teamId: 'glas', player: 'Luis Castillo', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 99, round: 10, pickInRound: 9, teamId: 'skenes', player: 'Tanner Bibee', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 100, round: 10, pickInRound: 10, teamId: 'senga', player: 'George Springer', pos: 'OF', cats: 'HR/R/RBI/SB' },
  { overall: 101, round: 11, pickInRound: 1, teamId: 'senga', player: 'Luke Keaschall', pos: '2B', cats: 'R/SB' },
  { overall: 102, round: 11, pickInRound: 2, teamId: 'skenes', player: 'Xavier Edwards', pos: 'SS', elig: ['2B','SS'], cats: 'R/SB/OBP' },
  { overall: 103, round: 11, pickInRound: 3, teamId: 'glas', player: 'Cam Schlittler', pos: 'SP', cats: 'K/ERA/WHIP' },
  { overall: 104, round: 11, pickInRound: 4, teamId: 'lets', player: 'Salvador Perez', pos: 'C', elig: ['C','1B'], cats: 'HR/RBI' },
  { overall: 105, round: 11, pickInRound: 5, teamId: 'keanu', player: 'Nico Hoerner', pos: '2B', cats: 'R/SB/OBP' },
  { overall: 106, round: 11, pickInRound: 6, teamId: 'vibes', player: 'Eugenio Suárez', pos: '3B', cats: 'HR/RBI' },
  { overall: 107, round: 11, pickInRound: 7, teamId: 'rain', player: 'Nick Lodolo', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 108, round: 11, pickInRound: 8, teamId: 'buckner', player: 'Steven Kwan', pos: 'OF', cats: 'R/SB/OBP' },
  { overall: 109, round: 11, pickInRound: 9, teamId: 'decoy', player: 'Jeremy Peña', pos: 'SS', cats: 'HR/R/RBI/SB' },
  { overall: 110, round: 11, pickInRound: 10, teamId: 'oneball', player: 'Chase Burns', pos: 'SP', elig: ['SP','RP'], cats: 'K/ERA/WHIP/QS' },
  { overall: 111, round: 12, pickInRound: 1, teamId: 'oneball', player: 'Nathan Eovaldi', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 112, round: 12, pickInRound: 2, teamId: 'decoy', player: 'Bubba Chandler', pos: 'SP', cats: 'K/ERA/WHIP' },
  { overall: 113, round: 12, pickInRound: 3, teamId: 'buckner', player: 'Adley Rutschman', pos: 'C', cats: 'OBP/HR/RBI' },
  { overall: 114, round: 12, pickInRound: 4, teamId: 'rain', player: 'Michael Harris II', pos: 'OF', cats: 'HR/R/RBI/SB' },
  { overall: 115, round: 12, pickInRound: 5, teamId: 'vibes', player: 'Teoscar Hernández', pos: 'OF', cats: 'HR/R/RBI' },
  { overall: 116, round: 12, pickInRound: 6, teamId: 'keanu', player: 'Matt Chapman', pos: '3B', cats: 'HR/R/RBI' },
  { overall: 117, round: 12, pickInRound: 7, teamId: 'lets', player: 'Ozzie Albies', pos: '2B', cats: 'HR/R/RBI/SB' },
  { overall: 118, round: 12, pickInRound: 8, teamId: 'glas', player: 'Brandon Woodruff', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 119, round: 12, pickInRound: 9, teamId: 'skenes', player: 'Max Muncy', pos: '3B', cats: 'HR/R/RBI/OBP' },
  { overall: 120, round: 12, pickInRound: 10, teamId: 'senga', player: 'Spencer Strider', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 121, round: 13, pickInRound: 1, teamId: 'senga', player: 'Michael Busch', pos: '1B', cats: 'HR/R/RBI' },
  { overall: 122, round: 13, pickInRound: 2, teamId: 'skenes', player: 'Marcus Semien', pos: '2B', cats: 'HR/R/RBI/SB' },
  { overall: 123, round: 13, pickInRound: 3, teamId: 'glas', player: 'Emmet Sheehan', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 124, round: 13, pickInRound: 4, teamId: 'lets', player: 'Raisel Iglesias', pos: 'RP', cats: 'SV/ERA/WHIP' },
  { overall: 125, round: 13, pickInRound: 5, teamId: 'keanu', player: 'Luis Robert Jr.', pos: 'OF', cats: 'HR/R/RBI/SB' },
  { overall: 126, round: 13, pickInRound: 6, teamId: 'vibes', player: 'Kyle Stowers', pos: 'OF', cats: 'HR/RBI' },
  { overall: 127, round: 13, pickInRound: 7, teamId: 'rain', player: 'Will Smith', pos: 'C', cats: 'HR/R/RBI/OBP' },
  { overall: 128, round: 13, pickInRound: 8, teamId: 'buckner', player: 'Daniel Palencia', pos: 'RP', cats: 'SV/K/ERA/WHIP' },
  { overall: 129, round: 13, pickInRound: 9, teamId: 'decoy', player: 'Brendan Donovan', pos: 'OF', elig: ['2B','SS','OF'], cats: 'R/OBP' },
  { overall: 130, round: 13, pickInRound: 10, teamId: 'oneball', player: 'Trey Yesavage', pos: 'SP', cats: 'K/ERA/WHIP' },
  { overall: 131, round: 14, pickInRound: 1, teamId: 'oneball', player: 'Sandy Alcantara', pos: 'SP', cats: 'ERA/WHIP/QS' },
  { overall: 132, round: 14, pickInRound: 2, teamId: 'decoy', player: 'Ryan Helsley', pos: 'RP', cats: 'SV/K/ERA/WHIP' },
  { overall: 133, round: 14, pickInRound: 3, teamId: 'buckner', player: 'Yandy Díaz', pos: '1B', cats: 'OBP/HR/RBI' },
  { overall: 134, round: 14, pickInRound: 4, teamId: 'rain', player: 'Zack Wheeler', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 135, round: 14, pickInRound: 5, teamId: 'vibes', player: 'Ryan Pepiot', pos: 'SP', cats: 'ERA/WHIP/QS' },
  { overall: 136, round: 14, pickInRound: 6, teamId: 'keanu', player: 'Gavin Williams', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 137, round: 14, pickInRound: 7, teamId: 'lets', player: 'Carlos Estévez', pos: 'RP', cats: 'SV/ERA/WHIP' },
  { overall: 138, round: 14, pickInRound: 8, teamId: 'glas', player: 'Shane McClanahan', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 139, round: 14, pickInRound: 9, teamId: 'skenes', player: 'Emilio Pagán', pos: 'RP', cats: 'SV/ERA/WHIP' },
  { overall: 140, round: 14, pickInRound: 10, teamId: 'senga', player: 'Seiya Suzuki', pos: 'OF', cats: 'HR/R/RBI/OBP' },
  { overall: 141, round: 15, pickInRound: 1, teamId: 'senga', player: 'Willy Adames', pos: 'SS', cats: 'HR/R/RBI/OBP' },
  { overall: 142, round: 15, pickInRound: 2, teamId: 'skenes', player: 'Agustín Ramírez', pos: 'C', cats: 'HR/RBI' },
  { overall: 143, round: 15, pickInRound: 3, teamId: 'glas', player: 'Michael King', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 144, round: 15, pickInRound: 4, teamId: 'lets', player: 'Josh Hader', pos: 'RP', cats: 'SV/K/ERA/WHIP' },
  { overall: 145, round: 15, pickInRound: 5, teamId: 'keanu', player: 'Pete Fairbanks', pos: 'RP', cats: 'SV/ERA/WHIP' },
  { overall: 146, round: 15, pickInRound: 6, teamId: 'vibes', player: 'Jeff Hoffman', pos: 'RP', cats: 'SV/K/ERA/WHIP' },
  { overall: 147, round: 15, pickInRound: 7, teamId: 'rain', player: 'Jo Adell', pos: 'OF', cats: 'HR/R/RBI' },
  { overall: 148, round: 15, pickInRound: 8, teamId: 'buckner', player: 'Trevor Rogers', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 149, round: 15, pickInRound: 9, teamId: 'decoy', player: 'Robbie Ray', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 150, round: 15, pickInRound: 10, teamId: 'oneball', player: 'Kenley Jansen', pos: 'RP', cats: 'SV/ERA/WHIP' },
  { overall: 151, round: 16, pickInRound: 1, teamId: 'oneball', player: 'Taylor Ward', pos: 'OF', cats: 'HR/R/RBI/OBP' },
  { overall: 152, round: 16, pickInRound: 2, teamId: 'decoy', player: 'Gerrit Cole', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 153, round: 16, pickInRound: 3, teamId: 'buckner', player: 'Brandon Nimmo', pos: 'OF', cats: 'R/OBP' },
  { overall: 154, round: 16, pickInRound: 4, teamId: 'rain', player: 'Trevor Story', pos: 'SS', cats: 'HR/R/RBI/SB' },
  { overall: 155, round: 16, pickInRound: 5, teamId: 'vibes', player: 'Ryan Walker', pos: 'RP', cats: 'ERA/WHIP' },
  { overall: 156, round: 16, pickInRound: 6, teamId: 'keanu', player: 'Drew Rasmussen', pos: 'SP', cats: 'ERA/WHIP/QS' },
  { overall: 157, round: 16, pickInRound: 7, teamId: 'lets', player: 'Kazuma Okamoto', pos: '1B', elig: ['1B','3B'], elig: ['1B','3B'], cats: 'HR/RBI' },
  { overall: 158, round: 16, pickInRound: 8, teamId: 'glas', player: 'Matt McLain', pos: '2B', cats: 'HR/R/RBI/SB' },
  { overall: 159, round: 16, pickInRound: 9, teamId: 'skenes', player: 'Ceddanne Rafaela', pos: 'OF', elig: ['2B','OF'], cats: 'R/SB' },
  { overall: 160, round: 16, pickInRound: 10, teamId: 'senga', player: 'Lawrence Butler', pos: 'OF', cats: 'HR/R/RBI/SB' },
  { overall: 161, round: 17, pickInRound: 1, teamId: 'senga', player: 'Tatsuya Imai', pos: 'SP', cats: 'K/ERA/WHIP' },
  { overall: 162, round: 17, pickInRound: 2, teamId: 'skenes', player: 'Ranger Suárez', pos: 'SP', cats: 'ERA/WHIP/QS' },
  { overall: 163, round: 17, pickInRound: 3, teamId: 'glas', player: 'Mike Trout', pos: 'OF', cats: 'HR/R/RBI/OBP' },
  { overall: 164, round: 17, pickInRound: 4, teamId: 'lets', player: 'Alec Burleson', pos: 'OF', elig: ['1B','OF'], cats: 'HR/RBI' },
  { overall: 165, round: 17, pickInRound: 5, teamId: 'keanu', player: 'Drake Baldwin', pos: 'C', cats: 'HR/RBI' },
  { overall: 166, round: 17, pickInRound: 6, teamId: 'vibes', player: 'MacKenzie Gore', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 167, round: 17, pickInRound: 7, teamId: 'rain', player: 'Jack Flaherty', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 168, round: 17, pickInRound: 8, teamId: 'buckner', player: 'Cade Horton', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 169, round: 17, pickInRound: 9, teamId: 'decoy', player: 'Dennis Santana', pos: 'RP', cats: 'ERA/WHIP' },
  { overall: 170, round: 17, pickInRound: 10, teamId: 'oneball', player: 'Trevor Megill', pos: 'RP', cats: 'ERA/WHIP' },
  { overall: 171, round: 18, pickInRound: 1, teamId: 'oneball', player: 'Willson Contreras', pos: '1B', cats: 'HR/RBI/OBP' },
  { overall: 172, round: 18, pickInRound: 2, teamId: 'decoy', player: 'Jac Caglianone', pos: '1B', elig: ['1B','OF'], cats: 'HR/RBI' },
  { overall: 173, round: 18, pickInRound: 3, teamId: 'buckner', player: 'Munetaka Murakami', pos: '1B', elig: ['1B','3B'], cats: 'HR/RBI' },
  { overall: 174, round: 18, pickInRound: 4, teamId: 'rain', player: 'Shota Imanaga', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 175, round: 18, pickInRound: 5, teamId: 'vibes', player: 'Hunter Greene', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 176, round: 18, pickInRound: 6, teamId: 'keanu', player: 'Andrew Abbott', pos: 'SP', cats: 'K/ERA/WHIP' },
  { overall: 177, round: 18, pickInRound: 7, teamId: 'lets', player: 'Jakob Marsee', pos: 'OF', cats: 'R/SB' },
  { overall: 178, round: 18, pickInRound: 8, teamId: 'glas', player: 'Robert Suarez', pos: 'RP', cats: 'SV/ERA/WHIP' },
  { overall: 179, round: 18, pickInRound: 9, teamId: 'skenes', player: 'Ian Happ', pos: 'OF', cats: 'HR/R/RBI/OBP' },
  { overall: 180, round: 18, pickInRound: 10, teamId: 'senga', player: 'Griffin Jax', pos: 'RP', cats: 'ERA/WHIP' },
  { overall: 181, round: 19, pickInRound: 1, teamId: 'senga', player: 'Bryce Miller', pos: 'SP', cats: 'ERA/WHIP/QS' },
  { overall: 182, round: 19, pickInRound: 2, teamId: 'skenes', player: 'Bryan Abreu', pos: 'RP', cats: 'ERA/WHIP' },
  { overall: 183, round: 19, pickInRound: 3, teamId: 'glas', player: 'Andy Pages', pos: 'OF', cats: 'HR/R/RBI' },
  { overall: 184, round: 19, pickInRound: 4, teamId: 'lets', player: 'Aaron Nola', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 185, round: 19, pickInRound: 5, teamId: 'keanu', player: 'Colson Montgomery', pos: '3B', elig: ['3B','SS'], cats: 'HR/R/RBI' },
  { overall: 186, round: 19, pickInRound: 6, teamId: 'vibes', player: 'Seranthony Domínguez', pos: 'RP', cats: 'ERA/WHIP' },
  { overall: 187, round: 19, pickInRound: 7, teamId: 'rain', player: 'Spencer Torkelson', pos: '1B', cats: 'HR/RBI' },
  { overall: 188, round: 19, pickInRound: 8, teamId: 'buckner', player: 'Colton Cowser', pos: 'OF', cats: 'HR/R/RBI/OBP' },
  { overall: 189, round: 19, pickInRound: 9, teamId: 'decoy', player: 'Konnor Griffin', pos: 'OF', elig: ['SS','OF'], cats: 'R/SB' },
  { overall: 190, round: 19, pickInRound: 10, teamId: 'oneball', player: 'Carlos Rodón', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 191, round: 20, pickInRound: 1, teamId: 'oneball', player: 'Otto Lopez', pos: '2B', elig: ['2B','SS'], cats: 'R/SB' },
  { overall: 192, round: 20, pickInRound: 2, teamId: 'decoy', player: 'Zach Eflin', pos: 'SP', cats: 'ERA/WHIP/QS' },
  { overall: 193, round: 20, pickInRound: 3, teamId: 'buckner', player: 'Robby Snelling', pos: 'SP', cats: 'K/ERA/WHIP' },
  { overall: 194, round: 20, pickInRound: 4, teamId: 'rain', player: 'Bobby Miller', pos: 'SP', cats: 'ERA/WHIP/QS' },
  { overall: 195, round: 20, pickInRound: 5, teamId: 'vibes', player: 'Shane Bieber', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 196, round: 20, pickInRound: 6, teamId: 'keanu', player: 'Edward Cabrera', pos: 'SP', cats: 'K/ERA/WHIP' },
  { overall: 197, round: 20, pickInRound: 7, teamId: 'lets', player: 'Matthew Boyd', pos: 'SP', cats: 'ERA/WHIP/QS' },
  { overall: 198, round: 20, pickInRound: 8, teamId: 'glas', player: 'Noelvi Marte', pos: '3B', elig: ['3B','OF'], cats: 'HR/R/RBI' },
  { overall: 199, round: 20, pickInRound: 9, teamId: 'skenes', player: 'Addison Barger', pos: '3B', elig: ['3B','OF'], cats: 'HR/R/RBI' },
  { overall: 200, round: 20, pickInRound: 10, teamId: 'senga', player: 'Paul Sewald', pos: 'RP', cats: 'SV/ERA/WHIP' },
  { overall: 201, round: 21, pickInRound: 1, teamId: 'senga', player: 'Kris Bubic', pos: 'SP', cats: 'ERA/WHIP/QS' },
  { overall: 202, round: 21, pickInRound: 2, teamId: 'skenes', player: 'Abner Uribe', pos: 'RP', cats: 'ERA/WHIP' },
  { overall: 203, round: 21, pickInRound: 3, teamId: 'glas', player: 'Zac Gallen', pos: 'SP', cats: 'ERA/WHIP/QS' },
  { overall: 204, round: 21, pickInRound: 4, teamId: 'lets', player: 'Ryne Nelson', pos: 'SP', elig: ['SP','RP'], cats: 'ERA/WHIP' },
  { overall: 205, round: 21, pickInRound: 5, teamId: 'keanu', player: 'Shane Baz', pos: 'SP', cats: 'K/ERA/WHIP' },
  { overall: 206, round: 21, pickInRound: 6, teamId: 'vibes', player: 'Joe Musgrove', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 207, round: 21, pickInRound: 7, teamId: 'rain', player: 'Mike Burrows', pos: 'SP', elig: ['SP','RP'], elig: ['SP','RP'], cats: 'K/ERA/WHIP' },
  { overall: 208, round: 21, pickInRound: 8, teamId: 'buckner', player: 'Joey Cantillo', pos: 'SP', elig: ['SP','RP'], cats: 'K/ERA/WHIP' },
  { overall: 209, round: 21, pickInRound: 9, teamId: 'decoy', player: 'Brady Singer', pos: 'SP', cats: 'ERA/WHIP/QS' },
  { overall: 210, round: 21, pickInRound: 10, teamId: 'oneball', player: 'Brenton Doyle', pos: 'OF', cats: 'HR/R/SB' },
  { overall: 211, round: 22, pickInRound: 1, teamId: 'oneball', player: 'Connelly Early', pos: 'SP', cats: 'ERA/WHIP' },
  { overall: 212, round: 22, pickInRound: 2, teamId: 'decoy', player: 'Cole Young', pos: '2B', cats: 'R/SB' },
  { overall: 213, round: 22, pickInRound: 3, teamId: 'buckner', player: 'Parker Messick', pos: 'SP', cats: 'K/ERA/WHIP' },
  { overall: 214, round: 22, pickInRound: 4, teamId: 'rain', player: 'Roki Sasaki', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 215, round: 22, pickInRound: 5, teamId: 'vibes', player: 'Spencer Schwellenbach', pos: 'SP', cats: 'ERA/WHIP/QS' },
  { overall: 216, round: 22, pickInRound: 6, teamId: 'keanu', player: 'Noah Cameron', pos: 'SP', cats: 'ERA/WHIP' },
  { overall: 217, round: 22, pickInRound: 7, teamId: 'lets', player: 'José Caballero', pos: '2B', elig: ['2B','3B','SS','OF'], cats: 'R/SB' },
  { overall: 218, round: 22, pickInRound: 8, teamId: 'glas', player: 'Mitch Keller', pos: 'SP', cats: 'ERA/WHIP/QS' },
  { overall: 219, round: 22, pickInRound: 9, teamId: 'skenes', player: 'Adolis García', pos: 'OF', cats: 'HR/R/RBI' },
  { overall: 220, round: 22, pickInRound: 10, teamId: 'senga', player: 'Kyle Manzardo', pos: '1B', cats: 'HR/RBI' },
  { overall: 221, round: 23, pickInRound: 1, teamId: 'senga', player: 'Brayan Bello', pos: 'SP', cats: 'ERA/WHIP/QS' },
  { overall: 222, round: 23, pickInRound: 2, teamId: 'skenes', player: 'Kodai Senga', pos: 'SP', cats: 'K/ERA/WHIP' },
  { overall: 223, round: 23, pickInRound: 3, teamId: 'glas', player: 'Kevin McGonigle', pos: 'SS', cats: 'R/SB' },
  { overall: 224, round: 23, pickInRound: 4, teamId: 'lets', player: 'Shane Smith', pos: 'SP', cats: 'ERA/WHIP' },
  { overall: 225, round: 23, pickInRound: 5, teamId: 'keanu', player: 'Michael Wacha', pos: 'SP', cats: 'ERA/WHIP/QS' },
  { overall: 226, round: 23, pickInRound: 6, teamId: 'vibes', player: 'Corbin Burnes', pos: 'SP', cats: 'K/ERA/WHIP/QS' },
  { overall: 227, round: 23, pickInRound: 7, teamId: 'rain', player: 'Merrill Kelly', pos: 'SP', cats: 'ERA/WHIP/QS' },
  { overall: 228, round: 23, pickInRound: 8, teamId: 'buckner', player: 'Jack Leiter', pos: 'SP', cats: 'K/ERA/WHIP' },
  { overall: 229, round: 23, pickInRound: 9, teamId: 'decoy', player: 'Colt Emerson', pos: 'SS', cats: 'R/SB' },
  { overall: 230, round: 23, pickInRound: 10, teamId: 'oneball', player: 'Samuel Basallo', pos: 'C', cats: 'HR/RBI' }
];