// ═══════════════════════════════════════════
// DATA CONSTANTS
// ═══════════════════════════════════════════

const TEAMS = [
  { id: 'senga',   name: 'Busch Latte',                 pick: 1, manager: '' },
  { id: 'skenes',  name: "Skenes'n on deez Hoerners",  pick: 2, manager: '' },
  { id: 'glas',    name: '877-Glas-Now',                pick: 3, manager: '' },
  { id: 'lets',    name: 'LetsPlayMajorLeagueBaseball', pick: 4, manager: '' },
  { id: 'keanu',   name: 'Keanu Reeves',                pick: 5, manager: '' },
  { id: 'vibes',   name: 'Good Vibes Only',             pick: 6, manager: '' },
  { id: 'rain',    name: 'Rain City Bombers',           pick: 7, manager: '' },
  { id: 'buckner', name: 'The Buckner Boots',           pick: 8, manager: 'Michael' },
  { id: 'decoy',   name: 'Decoy',                       pick: 9, manager: '' },
  { id: 'oneball', name: 'One Ball Two Strikes',        pick: 10, manager: '' },
];

const STANDINGS_2025 = [
  { teamId: 'lets',    rank: 1, record: '123-71-16', pct: '.624', moves: 81 },
  { teamId: 'oneball', rank: 2, record: '117-76-17', pct: '.598', moves: 63 },
  { teamId: 'glas',    rank: 3, record: '105-92-13', pct: '.531', moves: 94 },
  { teamId: 'vibes',   rank: 4, record: '99-98-13',  pct: '.502', moves: 101 },
  { teamId: 'decoy',   rank: 5, record: '107-89-14', pct: '.543', moves: 92 },
  { teamId: 'keanu',   rank: 6, record: '109-92-9',  pct: '.540', moves: 36 },
  { teamId: 'senga',   rank: 7, record: '85-115-10', pct: '.429', moves: 60 }, // fka Senga man watchu smokin?
  { teamId: 'buckner', rank: 8, record: '70-119-21', pct: '.383', moves: 50 },
  { teamId: 'rain',    rank: 9, record: '80-118-12', pct: '.410', moves: 17 },
  { teamId: 'skenes',  rank: 10, record: '87-112-11', pct: '.440', moves: 82 },
];

const REPEAT_PICKS = [
  { player: 'Adley Rutschman',    teamId: 'buckner', r25: 7,  r26: 12, diff: 5 },
  { player: 'Cristopher Sánchez', teamId: 'keanu',   r25: 14, r26: 3,  diff: -11 },
  { player: 'Jesús Luzardo',      teamId: 'lets',    r25: 19, r26: 7,  diff: -12 },
  { player: 'Joe Ryan',           teamId: 'lets',    r25: 8,  r26: 6,  diff: -2 },
  { player: 'Ozzie Albies',       teamId: 'lets',    r25: 5,  r26: 12, diff: 7 },
  { player: 'Brent Rooker',       teamId: 'vibes',   r25: 7,  r26: 4,  diff: -3 },
  { player: 'Eugenio Suárez',     teamId: 'vibes',   r25: 16, r26: 11, diff: -5 },
  { player: 'Corbin Burnes',      teamId: 'vibes',   r25: 4,  r26: 23, diff: 19 },
  { player: 'Michael King',       teamId: 'glas',    r25: 6,  r26: 15, diff: 9 },
  { player: 'Robert Suarez',      teamId: 'glas',    r25: 15, r26: 18, diff: 3 },
  { player: 'Carlos Rodón',       teamId: 'oneball', r25: 14, r26: 19, diff: 5 },
  { player: 'Will Smith',         teamId: 'rain',    r25: 13, r26: 13, diff: 0 },
  { player: 'Roki Sasaki',        teamId: 'rain',    r25: 10, r26: 22, diff: 12 },
  { player: 'Kyle Manzardo',      teamId: 'senga',   r25: 21, r26: 22, diff: 1 },
  { player: 'Zach Eflin',         teamId: 'decoy',   r25: 15, r26: 20, diff: 5 },
];

const BUCKNER_2026 = [
  { round: 1, pick: 8, player: 'Kyle Tucker', pos: 'OF', note: '' },
  { round: 2, pick: 13, player: 'Gunnar Henderson', pos: 'SS', note: '' },
  { round: 3, pick: 28, player: 'Ketel Marte', pos: '2B', note: '' },
  { round: 4, pick: 33, player: 'Logan Webb', pos: 'SP', note: '' },
  { round: 5, pick: 48, player: 'Framber Valdez', pos: 'SP', note: 'QS machine' },
  { round: 6, pick: 53, player: 'Chris Sale', pos: 'SP', note: 'K upside' },
  { round: 7, pick: 68, player: 'CJ Abrams', pos: 'SS', note: '' },
  { round: 8, pick: 73, player: 'Corey Seager', pos: 'SS', note: 'Steal of draft' },
  { round: 9, pick: 88, player: 'Devin Williams', pos: 'RP', note: 'Closer 1' },
  { round: 10, pick: 93, player: 'Alex Bregman', pos: '3B', note: 'OBP anchor' },
  { round: 11, pick: 108, player: 'Steven Kwan', pos: 'OF', note: 'OBP/SB' },
  { round: 12, pick: 113, player: 'Adley Rutschman', pos: 'C', note: '2025 keeper' },
  { round: 13, pick: 128, player: 'Daniel Palencia', pos: 'RP', note: 'Closer 2' },
  { round: 14, pick: 133, player: 'Yandy Díaz', pos: '1B', note: 'OBP elite' },
  { round: 15, pick: 148, player: 'Trevor Rogers', pos: 'SP', note: '' },
  { round: 16, pick: 153, player: 'Brandon Nimmo', pos: 'OF', note: 'OBP depth' },
  { round: 17, pick: 168, player: 'Cade Horton', pos: 'SP', note: '' },
  { round: 18, pick: 173, player: 'Munetaka Murakami', pos: '1B', note: 'Power upside' },
  { round: 19, pick: 188, player: 'Colton Cowser', pos: 'OF', note: '' },
  { round: 20, pick: 193, player: 'Robby Snelling', pos: 'SP', note: '' },
  { round: 21, pick: 208, player: 'Joey Cantillo', pos: 'SP', note: '' },
  { round: 22, pick: 213, player: 'Parker Messick', pos: 'SP', note: 'Opening Day rotation' },
  { round: 23, pick: 228, player: 'Jack Leiter', pos: 'SP', note: '' },
];

const TEAM_GRADES = [
  { teamId: 'oneball', grade: 'A',
    analysis: '<strong>Best all-around draft.</strong> Skubal + Yamamoto elite SP duo. Ramírez anchors everywhere including SB/OBP. Olson/Duran/Greene power depth. Bednar + Jansen lock down SV. Late adds (Burns, Eovaldi) fill rotation with high-floor arms.',
    strengths: ['HR','RBI','K','QS','SV','OBP'], weaknesses: ['C depth'] },
  { teamId: 'vibes', grade: 'A-',
    analysis: '<strong>OBP monster with elite SP depth.</strong> Harper/Betts/Altuve best OBP trio in the league. Crochet anchors 10+ deep SP corps (Bradish, Cease, Gore, Pepiot, Bieber, Schwellenbach, Burnes). Drafted Corbin Burnes again in R23 — 19 rounds later than 2025\'s R4 pick.',
    strengths: ['OBP','ERA','WHIP','QS','K','SP depth'], weaknesses: ['SB','OF depth'] },
  { teamId: 'buckner', grade: 'A-',
    analysis: '<strong>Best OBP-format exploitation.</strong> Tucker/Henderson 1-2 punch is elite. Marte/Bregman/Kwan/Rutschman/Nimmo/Cowser project for league\'s highest OBP. Webb + Valdez + Sale = QS factory. Williams + Palencia lock SV. 6 late SP lottery tickets for upside. Only Rutschman returns from 2025.',
    strengths: ['OBP','QS','SV','R','depth'], weaknesses: ['1B power','SB depth'] },
  { teamId: 'decoy', grade: 'B+',
    analysis: '<strong>Mason Miller is the league\'s best closer.</strong> Acuña bounce-back potential makes this boom-or-bust. Cole/Glasnow/Snell elite SP trio when healthy. Risk is health — Acuña, Glasnow, Cole all fragile. If healthy, this is an A team.',
    strengths: ['SV','K','SP upside','HR'], weaknesses: ['health risk','OBP','C'] },
  { teamId: 'glas', grade: 'B+',
    analysis: '<strong>Judge + Ohtani (Pitcher) most unique two-way stack.</strong> Ragans/Castillo/Ohtani(P) elite K upside. SP depth runs through Woodruff, McClanahan, Sheehan, King, Gallen, Keller. Re-drafted Michael King (R6→R15) and Robert Suarez (R15→R18). Pitching volume is absurd.',
    strengths: ['K','QS','ERA','WHIP','HR'], weaknesses: ['SB','MI health','OF depth'] },
  { teamId: 'lets', grade: 'B',
    analysis: '<strong>The defending champs ran it back.</strong> Drafted Elly again (now R1 vs R7 in 2025). Kept Joe Ryan (R8→R6), Luzardo (R19→R7), and Albies (R5→R12). 3 closers (Iglesias, Estévez, Hader) lock SV. SP depth is the worry — no true ace after Ryan/Luzardo.',
    strengths: ['SB','SV','HR','RBI'], weaknesses: ['K','QS','SP depth','ERA risk'] },
  { teamId: 'keanu', grade: 'B',
    analysis: '<strong>Soto + Schwarber best OBP duo outside Buckner.</strong> Promoted Cristopher Sánchez 11 rounds (R14→R3) — biggest single-player bet in the draft. Fried/Peralta give K upside. Chapman + Fairbanks provide saves. Middle is volatile (Buxton, Luis Robert, Merrill).',
    strengths: ['OBP','HR','SV','QS'], weaknesses: ['consistency','SB','C'] },
  { teamId: 'skenes', grade: 'B',
    analysis: '<strong>Witt/Yordan/Devers/Freeman most loaded power core.</strong> Complete roster overhaul — zero repeat picks from 2025 (only team to do this). Muñoz saves, Gilbert/Gausman/Pivetta/Bibee SP depth. Back half is dart throws (Edwards, Rafaela, Barger, García).',
    strengths: ['HR','R','RBI','SV'], weaknesses: ['C depth','SP ace','ERA risk','OBP'] },
  { teamId: 'rain', grade: 'B-',
    analysis: '<strong>Skenes elite SP1 but health risk everywhere.</strong> deGrom/Wheeler/Imanaga good but injury-prone. Tatis/Lindor star power in lineup but Machado/Yelich declining. Only 17 waiver moves in 2025 — fewest in the league. Kept Will Smith in the exact same round (R13→R13) and Sasaki (R10→R22).',
    strengths: ['K','QS','HR','R'], weaknesses: ['SV','health risk','waiver activity'] },
  { teamId: 'senga', grade: 'C+',
    analysis: '<strong>Ohtani (Batter) carries everything.</strong> Rebranded from "Senga man watchu smokin?" to Busch Latte. Carroll/Chisholm/Springer give speed, Díaz locks saves. But SP depth is genuinely concerning — Hunter Brown and Kirby are fine, after that it\'s Strider (health), Imai, Bryce Miller, Bubic, Bello.',
    strengths: ['SB','SV','OBP'], weaknesses: ['SP depth','K','QS','2nd star'] },
];

// PROJECTED STANDINGS DATA (500 sim avg)
const PROJECTED = [
  { teamId: 'oneball', w: 127, l: 77, t: 16, pct: '.598', playoff: '100%', champ: '34.8%' },
  { teamId: 'vibes',   w: 127, l: 79, t: 14, pct: '.609', playoff: '100%', champ: '26.4%' },
  { teamId: 'buckner', w: 120, l: 85, t: 15, pct: '.580', playoff: '100%', champ: '19.0%' },
  { teamId: 'glas',    w: 109, l: 97, t: 14, pct: '.527', playoff: '95%',  champ: '10.8%' },
  { teamId: 'decoy',   w: 103, l: 102, t: 15, pct: '.502', playoff: '81%', champ: '4.4%' },
  { teamId: 'keanu',   w: 99,  l: 106, t: 15, pct: '.484', playoff: '61%', champ: '2.6%' },
  { teamId: 'lets',    w: 98,  l: 109, t: 13, pct: '.475', playoff: '51%', champ: '1.6%' },
  { teamId: 'skenes',  w: 90,  l: 115, t: 15, pct: '.443', playoff: '12%', champ: '0.2%' },
  { teamId: 'rain',    w: 80,  l: 126, t: 14, pct: '.395', playoff: '1%',  champ: '0.2%' },
  { teamId: 'senga',   w: 74,  l: 133, t: 13, pct: '.365', playoff: '0%',  champ: '0%' },
];

const BUCKNER_SCHEDULE = [
  { week: 1, opp: 'oneball', diff: 'tough' },
  { week: 2, opp: 'lets', diff: 'even' },
  { week: 3, opp: 'senga', diff: 'easy' },
  { week: 4, opp: 'skenes', diff: 'easy' },
  { week: 5, opp: 'vibes', diff: 'tough' },
  { week: 6, opp: 'decoy', diff: 'even' },
  { week: 7, opp: 'keanu', diff: 'even' },
  { week: 8, opp: 'glas', diff: 'even' },
  { week: 9, opp: 'rain', diff: 'easy' },
  { week: 10, opp: 'oneball', diff: 'tough' },
  { week: 11, opp: 'lets', diff: 'even' },
  { week: 12, opp: 'senga', diff: 'easy' },
  { week: 13, opp: 'skenes', diff: 'easy' },
  { week: 14, opp: 'vibes', diff: 'tough' },
  { week: 15, opp: 'decoy', diff: 'even' },
  { week: 16, opp: 'keanu', diff: 'even' },
  { week: 17, opp: 'glas', diff: 'even' },
  { week: 18, opp: 'rain', diff: 'easy' },
  { week: 19, opp: 'oneball', diff: 'tough' },
  { week: 20, opp: 'lets', diff: 'even' },
  { week: 21, opp: 'senga', diff: 'easy' },
  { week: 22, opp: 'skenes', diff: 'easy' },
];
